# Generated by Django 2.2 on 2019-04-09 20:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15)),
                ('created_date', models.DateTimeField(verbose_name=datetime.datetime(2019, 4, 9, 20, 51, 1, 516110, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_title', models.CharField(max_length=20)),
                ('production', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('added_date', models.DateTimeField(verbose_name=datetime.datetime(2019, 4, 9, 20, 51, 1, 516550, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_library.User')),
            ],
        ),
    ]
