# Generated by Django 2.2 on 2019-04-09 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('film_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='added_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 4, 9, 20, 52, 19, 946719, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 4, 9, 20, 52, 19, 946269, tzinfo=utc)),
        ),
    ]
